name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        default: YYYY.MM.DD
        description: 'The SourcePP version'
      release:
        type: boolean
        required: true
        default: false
        description: 'Push the release to all channels (GitHub, PyPI)'

jobs:
  python_build_sdist:
    name: '[Python] Build SDist'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '${{github.workspace}}/lang/python'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Configure CMake
        working-directory: '${{github.workspace}}'
        run: cmake -G "Unix Makefiles" -B build -DCMAKE_BUILD_TYPE=Release -DSOURCEPP_BUILD_PYTHON_WRAPPERS=ON -DSOURCEPP_VERSION="${{inputs.version}}"

      - name: Build SDist
        run: |
          pipx run build --sdist

      - name: Check Metadata
        run: |
          pipx run twine check dist/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-dist-sdist
          path: '${{github.workspace}}/lang/python/dist/*.tar.gz'

  python_build_bdist:
    name: '[Python] Build BDist (${{matrix.os}})'
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: '${{github.workspace}}/lang/python'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Configure CMake
        working-directory: '${{github.workspace}}'
        run: cmake -G "Unix Makefiles" -B build -DCMAKE_BUILD_TYPE=Release -DSOURCEPP_BUILD_PYTHON_WRAPPERS=ON -DSOURCEPP_VERSION="${{inputs.version}}"

      - name: Build BDist
        run: |
          python -m pip install cibuildwheel==3.2.0
          python -m cibuildwheel --output-dir dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-dist-bdist-${{matrix.os}}
          path: '${{github.workspace}}/lang/python/dist/*.whl'

  python_upload_release:
    name: '[Python] Upload to PyPI'
    if: inputs.release
    needs:
     - python_build_sdist
     - python_build_bdist
    runs-on: ubuntu-latest
    environment:
      name: pypi-release
      url: https://pypi.org/p/sourcepp
    permissions:
      id-token: write
    steps:
      - name: Download Wheels
        uses: actions/download-artifact@v4
        with:
          pattern: python-dist-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
